[build]
  command = "python manage.py collectstatic --noinput"
  publish = "staticfiles"

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/*"
  to = "templates/index.html"
  status = 200
